
# Nombre del Projecto
#Version  
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# Esta configuración configura qué "perfil" utiliza dbt para este proyecto.
profile: 'default'

# Estas configuraciones especifican dónde debe buscar dbt los distintos tipos de archivos.
# La configuración `source-paths`, por ejemplo, indica que los modelos de este proyecto se pueden
# encontrar en el directorio "models/". ¡Probablemente no necesitarás cambiarlos!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # Directorio que almacenará los archivos SQL compilados
clean-targets:         # Direcciorio que se elimina
  - "target"
  - "dbt_packages"



models:
  my_new_project:
   
    example:
      materialized: view
